### ISSUE TITLE
selenium-webdriver is running geckodriver-update instead of geckodriver

### ISSUE THREAD

**Issue by thbar** [DevicoSolutions/geckodriver-helper#1]
I spent a fair bit of time debugging this, so I thought I would report it here.

In selenium webdriver, there is an automated detect of gecko driver using [this code](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/firefox/service.rb#L29), pasted here for the record:

```ruby
class Service < WebDriver::Service
  DEFAULT_PORT = 4444
  @executable = 'geckodriver*'.freeze
```

The last line is picking `geckodriver-update` instead of `geckodriver` when `geckodriver-helper` is installed (not on Mac OS X, but on an Ubuntu installation).

I also found out that this can be circumvented using this option:

```ruby
Capybara.register_driver :selenium_firefox do |app|
  Capybara::Selenium::Driver.new(app, browser: :firefox, profile: profile, 
    driver_path: '/app/shared/bundle/ruby/x.y.z/bin/geckodriver')
end
```

I thought I would report that - I realise that the culprit is inside selenium-webdriver, yet maybe a readme note on this project could help too?

**Comment by thbar** [comment]
Here is an improved hot-fix:

```ruby
Capybara.register_driver :selenium_firefox do |app|
  Capybara::Selenium::Driver.new(app, browser: :firefox, profile: profile,
    driver_path: Gem.bin_path("geckodriver-helper", "geckodriver")
  )
end
```

**Comment by grzuy** [comment]
@thbar Thank you.

For anyone interested, here is an adaptation of the above fix but for a __rails__ app using __System Tests__.

```diff
 class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
-  driven_by :selenium, using: :firefox
+  driven_by :selenium, using: :firefox, options: { driver_path: Gem.bin_path("geckodriver-helper", "geckodriver") })
```

**Comment by dmitryreznik** [comment]
@thbar could you please create PR ?

**Comment by dmitryreznik** [comment]
@thbar Should be fixed now.
